### ISSUE TITLE
get_element的使用問題。

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#11]
get_element這個函數在zone,py中使用時，是沒有給輸入的。
character.get_element():

但在character.py中定義時，有要求輸入一個 'GeniusGame'型別:

    def get_element(self, game: 'GeniusGame'):
        return [self.element]

這使的此程式在我的設備上運行時出現了錯誤。
目前看下來再character.py當中的get_element函數其實並沒有用到game: 'GeniusGame'，我並不清楚它的作用，請問這是可以刪的嗎?

如果可以刪，那就修改成:

    def get_element(self):
        return [self.element]

如果不能刪，zone.py中的

    def __init__(self, game: 'GeniusGame', player: 'GeniusPlayer') -> None:
        self.player = player
        '''
            我们用一个[16, 9]的数组来维护骰子
        '''
        self.dice_num = 0
        self.space = np.zeros((MAX_DICE, DICENUM+1)).astype(np.int16)
        for i in range(MAX_DICE):
            self.space[i][-1] = -1
        self.sort_map = self.get_sort_map()

也應該補上缺失的self.game = game。

    def __init__(self, game: 'GeniusGame', player: 'GeniusPlayer') -> None:
        self.player = player
        self.game = game
        '''
            我们用一个[16, 9]的数组来维护骰子
        '''
        self.dice_num = 0
        self.space = np.zeros((MAX_DICE, DICENUM+1)).astype(np.int16)
        for i in range(MAX_DICE):
            self.space[i][-1] = -1
        self.sort_map = self.get_sort_map()

並在def get_sort_map(self):當中的get_element():輸入self.game。
修改前

                for element in character.get_element():
                    sort_map[ElementToDice[element].value] += 200

修改後

                for element in character.get_element(self.game):
                    sort_map[ElementToDice[element].value] += 2000

**Comment by WentDong** [comment]
Fixed !
