### ISSUE TITLE
手牌全是花海甘露之光

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#12]
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/be98a836-d224-4090-900c-b17786689a43)

自從前幾天更新了main.py後就產生了其中一個玩家手牌中全是花海甘露之光的問題。

直到6/26我手上的main.py都是沒問題的。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/4dbc3933-a944-4ccc-9958-72be793d6c48)

**Comment by WentDong** [comment]
你可以直接修改 `main.py` 170行附近的组卡代码，任意的修改牌组。
