### ISSUE TITLE
play.py 疑似錯字導致調和骰子出現錯誤

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#13]
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/dd5dee7c-0501-4efb-a7f6-252323830862)
在調和骰子時出現了錯誤。

gnius-invokation-main\gnius-invokation\game\play.py

類別'GeniusPlayer'在方法play_card中調用了一個名叫tune_or_discard_cards的屬性。(204行)

    def play_card(self, game: 'GeniusGame'):
        '''
            标准行动: 打出手牌/调和手牌
        '''
        self.use_dice(game)
        idx = game.current_action.choice_idx
        card: ActionCard = self.hand_zone.use(idx)
        game.current_card = card
        if game.current_action.target_type == ActionTarget.DICE_REGION:
            self.tune_or_discard_cards.append(card)
            card.on_tuning(game)

但是類別中並沒有tune_or_discard_cards這個屬性，但有一個名稱相似的屬性，self.tunr_or_discard_cards在def init_define(self):中(91行)

將其修改後調和可以正常進行。

**Comment by WentDong** [comment]
Fixed！
