### ISSUE TITLE
因未知原因，班尼特無法開大招。

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#15]
原本缺少火元素骰，因此班尼特無法開大。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/c939f7e8-155a-43fe-9147-54f57422b3ea)

將手牌調和後，我取得了4個有效骰，但選項中仍然沒有班尼特可開大的選項。

![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/9c0aad7f-be47-4e78-83ce-a31cb428a5d7)
之後我直接讓雙方都結束回合，進入下一回合後，經過重擲骰子，班尼特就能開大了。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/3ee61747-50cd-423a-a320-babd1f74b091)

**Comment by jeffrey-hsiao** [comment]
更新，就算一開始就有足夠元素骰，班尼特也會遇到無法開大的情況，並且可能會持續好幾個回合。
有成功藉由換人後結束回合才成功使他多出開大的選項。

並且，後續就算出現了開大的選項，選取4個有效骰也會被視為無效操作。

**Comment by flick-ai** [comment]
您好，这个问题是由于班尼特大招的骰子种类要求存在纰漏导致的，目前已修复，感谢您的支持！
