### ISSUE TITLE
調和錯誤

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#16]
在選取骰子調和時遇到沒法正常調和的錯誤。
如畫面所示，我想用自由的新風來調和骰子。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/6826c0d7-6fa2-4e9c-9b09-d13f639ec814)

前面5骰為有效骰。
但無論怎麼選擇都無法將骰後幾個骰子調和，並且最後還把自由的新風打了出去。0
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
7
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
7
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
6
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
5
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
4
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
3
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
4
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
0
您输入的内容无效，请重新输入
根据您选择的行动，您可以选择以下目标
1.选择本方
13.选择操作本方骰子
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/f42e4c23-ff98-4191-863a-c34a09374c47)

**Comment by flick-ai** [comment]
您可能需要先确定是否调和手牌，如果调和手牌需要先选择13操作本方骰子，然后选择调和哪一个骰子。这里的复杂操作我们后续将进行改进，谢谢。
