### ISSUE TITLE
出戰狀態優先級錯誤

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#17]
班尼特大招的效果是，血量在7以下時，每次行動會回復2點血量。
可莉大招的效果是，當敵人行動後，爆炸會對敵人出戰角色造成2點火元素傷害。

通常來說，這兩者會相互抵消，誰先觸發好像不是很重要。
但如果對於本身寫量已經在2血或以下時，{可莉大招先-2，班尼特在+2}，或是{班尼特大招先+2，可莉大招在-2}差異就很大了。

如果可莉大招先-2，那麼敵人就會死亡，且不會回血。
如果班尼特大招先+2，那麼敵人會先回復2點血後再扣掉2點血，因此避免掉死亡。

而，可莉大招與班尼特大招觸發的順序，「取決於兩個大招是誰先開的」
先開的大招效果會先觸發。

而模擬器的狀況卻是可莉絕對優先。
實驗步驟如下

1,把班尼特壓到剩下2血。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/c54b2b1e-d2b6-49b5-bf62-d9fd3e5c84b3)

2,班尼特開大，回2血。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/83e58e63-763c-4d72-a436-2beef9474b9b)

3,可莉開大，把班尼特壓到剩下2血。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/63cd4f57-9da2-4a17-bdec-6bf24767f238)

4,班尼特平a。
![image](https://github.com/flick-ai/Genius-Invokation/assets/129878697/14cdef98-bc45-43b6-ba81-5355eea0a5b9)

可以清楚的看到，班尼特先開了大招獲得鼓舞領域，之後才吃到蹦蹦炸彈，照理來說剩下2血的班尼特應該先吃到 鼓舞領域的2點回血後，再受到蹦蹦炸彈的2點傷害攻擊，照理來說不會死亡，但很顯然的，班尼特在這裡死亡了，所以兩者效果的觸發順序是錯的。

這非常重要，因為所有的陣營狀態全都是符合先取得者先觸發的規則(角色個人狀態另計)，包誇七七大招，雷蠍大招，甚至是事件牌，風與自由，鶴歸之時等等，都有先取得的效果會先觸發的特性，這非常重要，不同順序很容易導致截然不同的戰局。

類似的事情還有
女士e技能的極寒效果(結束階段後扣掉1點血
舊版甘露花海之光(結束階段回復1點血
兩者誰先誰後也是關乎到角色會不會死，並且同樣的，如果已經事先裝備聖遺物甘露花海之光，受到攻擊後，會是先回血。
反之則事先受傷
(現代則因為效果改成受到傷害後才觸發，所以不清楚到底會發生甚麼。

風與自由的行動後換人，其優先順序也會與可莉崩蹦的行動後攻擊具有觸發順序的極大差異。

**Comment by WentDong** [comment]
修了
看看该问题是否依旧存在

**Comment by flick-ai** [comment]
该问题应该已经得到修复，项目开始时我们受到文本“技能结算完成后”的影响，将其理解为一个单独的时刻，错误的理解了其先后顺序，导致纰漏。感谢您对火刻卡组的热爱
