### ISSUE TITLE
鼓舞領域似乎沒有id

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#19]
![image](https://github.com/user-attachments/assets/8b68b3dd-a82b-4919-925c-b88cdcb9d677)
如圖所示，我嘗試打印陣營狀態的id卻出現問題。

首先我嘗試列印的space屬於型別Combat_Status
![image](https://github.com/user-attachments/assets/f724cd84-3fa7-4732-af62-ffa1ea46eb55)

而從status.py嘗試去查看Combat_Status其實是能看到id的設計的，但不是self.id
![image](https://github.com/user-attachments/assets/cc986994-f9fa-43a6-94f0-44442abb1165)

而班尼特技能的鼓舞領域明顯的沒有id部分
![image](https://github.com/user-attachments/assets/3b7bc20a-84e8-4d62-be59-3cf8d2a60416)

稍微檢查了一下，除了鼓舞領域以外，有些狀態也是沒有ID的，例如魈的大招狀態(屬於Status)，但同時Status的類別設計中也包含了id，我不確定這是不是正常設計。

**Comment by WentDong** [comment]
此次版本更新中，对所有的实例均有明确、系统的编号，编号方式如下：

对于ID为xxxx的人物牌，或是ID为xxxxxx的行动牌，其衍生的各类内容的编号均基于这个ID得到：
- 对于Skill: id 为 xxxx**0**n, n 代表技能的编号；
- `Summon`: xxxx**1**n
- `Status`: xxxx**2**n
- `Combat_Status`: xxxx**3**n
- `Shield`: xxxx**4**n
- `Combat_Shield`: xxxx**5**n
- `Support`: xxxx**6**n
- `Card`: xxxx**7**n
- `Weapon`: xxxx**8**n
- `Artifact`: xxxx**9**n
