### ISSUE TITLE
七七e技能的召喚物沒有ID

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#20]
在測試讀取召喚物ID時發現七七的召喚物沒有ID，但相對的存水精靈的召喚物就有，請問ID是一個被廢棄的設定嗎?
所以未來RL打算以自然語言處理中的鑲入來進行嗎?

**Comment by flick-ai** [comment]
您好，您的三个问题我们都已经检查过。后边两个id的问题是因为状态、召唤物这些场上的内容本身是不具备ID信息的，我们后续便没有再维护这个变量，只对卡牌维护了id。我们也希望使用LLM来对状态、卡牌进行编码，或者使用one-hot，确实应该为所有可能出现的状态维护ID。我们将联合您的第一个武器的问题在下次更新中维护。感谢您的支持

**Comment by WentDong** [comment]
此次版本更新中，对所有的实例均有明确、系统的编号，编号方式如下：

对于ID为xxxx的人物牌，或是ID为xxxxxx的行动牌，其衍生的各类内容的编号均基于这个ID得到：

对于Skill: id 为 xxxx0n, n 代表技能的编号；
Summon: xxxx1n
Status: xxxx2n
Combat_Status: xxxx3n
Shield: xxxx4n
Combat_Shield: xxxx5n
Support: xxxx6n
Card: xxxx7n
Weapon: xxxx8n
Artifact: xxxx9n
