### ISSUE TITLE
卯師傅的效果似乎能無限觸發

### ISSUE THREAD

**Issue by jeffrey-hsiao** [flick-ai/Genius-Invokation#21]
如圖所示，本該每回和限1次發動的卯師傅發生了可無限生效的狀況
![image](https://github.com/user-attachments/assets/bd33c321-ef62-4b0b-a24b-9f8e5bfc8161)

![image](https://github.com/user-attachments/assets/5c91538c-8bcd-406a-9802-e9a07b308cd8)
![image](https://github.com/user-attachments/assets/7d2101e0-5092-4015-8ebd-e6ba28f74152)
![image](https://github.com/user-attachments/assets/e1df4659-e5a6-49d5-896e-d9ea9dd89030)
![image](https://github.com/user-attachments/assets/982b68ba-e085-4cfb-a682-29f0e34d92af)
![image](https://github.com/user-attachments/assets/d98ec6ea-c396-436f-984a-6cfbf8d90f64)

**Comment by WentDong** [comment]
已修复
