### ISSUE TITLE
BUG: 吃料理无法正常选取骰子导致卡死

### ISSUE THREAD

**Issue by RuibaiXu** [flick-ai/Genius-Invokation#3]
环境：在线网页端demo(https://flick-ai.github.io/Genius-Invokation-Website/)
描述：打出料理手牌时，选择料理手牌，确认->选择角色，确认->选择骰子，确认，但无法生效，右侧保持提示“您需要选择使用的1个CostType.WHITE骰子的位置”，不止1种料理有此BUG

**Comment by flick-ai** [comment]
感谢您对本仓库的使用和支持。该问题的出现是由于饱腹状态的显示所带来的问题，目前已经修复。网页版也将在今晚修复这个bug。如果您在使用中有任何的意见，希望您能积极的提出。我们的交流群二维码在主页的Attach链接下。

**Comment by Bluixe** [comment]
网页端bug已修复，非常感谢测试。

**Comment by RuibaiXu** [comment]
这个BUG好像在某些条件下又出现了
